name: Release CI 

on:
  push:
    tags:
      - 'v*' # Push events matching example v0.1.1
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prepare for libseccomp
      run: sudo apt-get install libseccomp-dev

    - name: Build
      run: cargo build --release --verbose

    - name: Run Tests
      run: CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='sudo -E' cargo test --verbose

    - run: mkdir artifact
    - run: tar -czf  artifact/oci-ftrace-syscall-analyzer-amd64.tar.gz -C target/release/ oci-ftrace-syscall-analyzer

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: oci-ftrace-syscall-analyzer.amd64 
        path: artifact/oci-ftrace-syscall-analyzer-amd64.tar.gz

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ github.ref }}
       release_name: Release ${{ github.ref }}
       draft: false
       prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifact/oci-ftrace-syscall-analyzer-amd64.tar.gz
        asset_name: oci-ftrace-syscall-analyzer-amd64.tar.gz
        asset_content_type: application
